# Generated by Django 3.2.20 on 2023-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_key', models.TextField(verbose_name='Ключ')),
                ('passphrase', models.CharField(max_length=100, verbose_name='Кодовое слово')),
                ('secret', models.TextField(verbose_name='Секрет')),
            ],
            options={
                'verbose_name': 'секрет',
                'verbose_name_plural': 'секреты',
            },
        ),
    ]
