# Generated by Django 3.2.20 on 2023-11-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='time_to_live',
            field=models.IntegerField(default=43200),
        ),
    ]
