# Generated by Django 3.2.20 on 2023-11-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0002_secret_time_to_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='generated_key',
            field=models.TextField(blank=True, null=True, verbose_name='Ключ'),
        ),
    ]
